- application/views/history.php
- application/views/parts.php
- application/views/template.php
> changed the rows from out of the template into the views

- application/controllers/Assembly.php
- application/models/Part.php
- application/models/Robot.php
- application/views/assembly.php
Assembly page now displays the robot parts along with a "suggested" robot. Build robot, use and scrap buttons have been added to page.
Maitiu Morton
> Assembly Page Added

- application/models/Robot.php
- application/views/assembly.php
Signed-off-by: Uitiam <maitiumorton@gmail.com>
> added Robot class fuctionality

- application/views/assembly.php
Signed-off-by: Uitiam <maitiumorton@gmail.com>
> Fixed the assembly page footer bug 

- application/models/History.php
- application/models/Part.php
- application/models/Robot.php
> Added comments and summation methods to models

- application/controllers/HistoryController.php
- application/models/History.php
- application/models/Part.php
- application/views/history.php
> redid the visuals of history and changed internals to support it

- application/controllers/Parts.php
- application/models/Part.php
- application/views/parts.php
> added missing part info and updated ui

- application/models/Part.php
- application/models/Robot.php
- application/views/assembly.php
Signed-off-by: Uitiam <maitiumorton@gmail.com>
> Added part data to Robot class also made Assembly view look better

- application/views/parts.php
> changed dropdown to carousel

- application/controllers/Welcome.php
- application/models/History.php
- application/views/landing.php
- application/views/template.php
- public/assets/css/style.css
Signed-off-by: Michael Goll <mike_g97@hotmail.com>
> Dashboard implementation

- data/schema.sql
> added database schema for all models

- application/config/autoload.php
- application/controllers/HistoryController.php
- application/models/History.php
- application/views/history.php
- data/schema.sql
> updated schema for new requirements

- .gitignore
- application/models/History.php
this should make it easy to add stuff to the history table
> added helpers to log the transactions from the other models

- application/config/autoload.php
- application/models/Company.php
> added a model to wrap the company database interaction

- application/controllers/Parts.php
- application/models/Part.php
> Fixed error with parts page

- application/controllers/Parts.php
> Changed curl to file_get_contents

- application/config/autoload.php
- application/config/routes.php
- application/controllers/History.php
- application/controllers/Parts.php
- application/controllers/Welcome.php
- application/models/HistoryModel.php
> fixed model and controller with odd naming; fixed sql insert

- application/controllers/History.php
- application/views/historySingle.php
- application/views/template.php
> history has methods to filter and paginate

- application/models/Part.php
> Fixed issues with data being escaped in database

- application/controllers/Parts.php
- application/models/Part.php
> Fixd error where history would double escape values

- application/controllers/Parts.php
- application/views/parts.php
> Added basic pagination for parts

- application/controllers/Parts.php
- application/views/parts.php
> Added pagination links for parts page

- application/models/Robot.php
> fixed part count not working

- application/controllers/History.php
> fixed the ordering for history

- application/models/ManageModel.php
Signed-off-by: Michael Goll <mike_g97@hotmail.com>
> Changed casing on table name.

- application/controllers/Assembly.php
- application/controllers/Parts.php
- application/models/Part.php
- application/views/assembly.php
- public/assets/js/assembly.js
Signed-off-by: Uitiam <maitiumorton@gmail.com>
> Added Recycle Feature

- application/controllers/Manage.php
- application/models/ManageModel.php
- public/assets/js/manage.js
Signed-off-by: Michael Goll <mike_g97@hotmail.com>
> Actually updates db api key now
